//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_50Ders.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMusteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMusteriler()
        {
            this.tblSatislar = new HashSet<tblSatislar>();
        }
    
        public int musteriID { get; set; }

        [Required(ErrorMessage ="Müþteri Adý Boþ Geçilemez!")]
        [StringLength(50,ErrorMessage ="Müþteri Adý En Fazla 50 Karakter Olmalýdýr")]
        public string musteriAd { get; set; }

        [Required(ErrorMessage = "Müþteri Soyadý Boþ Geçilemez!")]
        [StringLength(50, ErrorMessage = "Müþteri Soyadý En Fazla 50 Karakter Olmalýdýr")]
        public string musteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSatislar> tblSatislar { get; set; }
    }
}
